#
# Build stage
#
FROM maven:3.6.0-jdk-11-slim AS build

WORKDIR /home/app
# install dependencies
COPY pom.xml .
COPY ci_settings.xml .
RUN mvn dependency:go-offline -s ci_settings.xml --quiet

# build the application
COPY src /home/app/src
RUN mvn -f /home/app/pom.xml clean package -s /home/app/ci_settings.xml --quiet -DskipTests




# Package stage
#
FROM openjdk:11-jre-slim

WORKDIR /home/app
# init dirs
RUN mkdir data
RUN mkdir data/hdt-store

COPY --from=build /home/app/target/hdtSparqlEndpoint-*-SNAPSHOT.jar /usr/local/lib/hdtSparqlEndpoint-*-SNAPSHOT.jar

COPY --from=build /home/app/src/main/resources/application-prod.properties /home/app/application-prod.properties
EXPOSE 1234
RUN  apt-get update \
  && apt-get install -y wget \
  && rm -rf /var/lib/apt/lists/*

COPY loadData.sh .
RUN chmod +x loadData.sh
CMD ./loadData.sh
# ENTRYPOINT echo "Downloading the HDT index..." && wget --progress=bar:force:noscroll -O /home/app/data/hdt-store/index.hdt https://data.linkedopendata.eu/index_big.hdt \
#         && wget --progress=bar:force:noscroll -O /home/app/data/hdt-store/index.hdt.index.v1-1 https://data.linkedopendata.eu/index_big.hdt.index.v1-1 \
#         && echo "Starting HDT Sparql Service..." \
#         && java -Dspring.config.location=file:///home/app/application-prod.properties -jar /usr/local/lib/hdtSparqlEndpoint-*-SNAPSHOT.jar