#
# Build stage
#
FROM maven:3.6.0-jdk-11-slim AS build

WORKDIR /home/app
# install dependencies
COPY pom.xml .
COPY ci_settings.xml .
RUN mvn dependency:go-offline -s ci_settings.xml --quiet

# build the application
COPY src /home/app/src
RUN mvn -f /home/app/pom.xml clean package -s /home/app/ci_settings.xml --quiet -DskipTests


#
# Package stage
#
FROM openjdk:11-jre-slim

WORKDIR /home/app
# init dirs
RUN mkdir data
RUN mkdir data/hdt-store

COPY --from=build /home/app/target/hdtSparqlEndpoint-1.0.1-SNAPSHOT.jar /usr/local/lib/hdtSparqlEndpoint-1.0.1-SNAPSHOT.jar

COPY --from=build /home/app/src/main/resources/application-prod.properties /home/app/application-prod.properties
EXPOSE 1234
ENTRYPOINT ["java","-Dspring.config.location=file:///home/app/application-prod.properties","-jar","/usr/local/lib/hdtSparqlEndpoint-1.0.1-SNAPSHOT.jar"]