FROM qacompany/qendpoint

WORKDIR /app

COPY wikidata-prefixes.sparql .
COPY loadData.sh .
RUN chmod +x loadData.sh

ARG HDT_BASE=wikidata_truthy
ENV HDT_BASE ${HDT_BASE}

EXPOSE 1234
ENTRYPOINT ["/usr/bin/env"]

CMD ["/bin/sh", "-c", "./loadData.sh ${HDT_BASE} && java -jar -Xmx${MEM_SIZE} qendpoint.jar"]
