name: Sync dev and master branch

on:
  push:
    branches:
      - "master"

concurrency:
  group: ${{ github.ref }}-sync
  cancel-in-progress: true

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: pull-request
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "dev"
          pr_title: "Sync master into dev"
          pr_body: "Sync master into dev."
          pr_label: "sync"
          pr_assignee: "ate47"
          github_token: ${{ secrets.GITHUB_TOKEN }}
